shop/controllers/CabinetWalletController.php
<?php

namespace shop\controllers;

use avatar\controllers\actions\DefaultAjax;
use common\models\avatar\Currency;
use common\models\avatar\UserBill;
use common\models\avatar\UserBillMerchant;
use common\models\BillingMain;
use common\models\RequestInputRub;
use school\modules\sroutes\models\Arbitrator;
use school\modules\sroutes\models\Deal;
use school\modules\sroutes\models\DealStatus;
use common\models\investment\IcoRequest;
use common\models\investment\IcoRequestSuccess;
use common\models\PaySystemConfig;
use common\models\piramida\Billing;
use common\models\piramida\Wallet;
use common\models\UserAvatar;
use common\services\Security;
use cs\Application;
use cs\base\BaseController;
use cs\services\UploadFolderDispatcher;
use cs\services\VarDumper;
use cs\web\Exception;
use Yii;
use yii\base\UserException;
use yii\db\Connection;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\web\ErrorAction;
use yii\web\Response;

class CabinetWalletController extends \avatar\controllers\CabinetBaseController
{
    public function actions()
    {
        return [
            'send2' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\avatar\models\forms\SendAtom2',
                'formName' => 'SendAtom2',
            ],
            'market-buy' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\shop\models\validate\CabinetWalletMarketBuy',
            ]
        ];
    }

    public function actionIndex()
    {
        return $this->render();
    }

    public function actionItem($id)
    {
        try {
            $bill = UserBill::findOne($id);
        } catch (\Exception $e) {
            throw new Exception('Счет не найден');
        }

        /** @var UserAvatar $user */
        $user = Yii::$app->user->identity;
        // Если не (бухгалтер)
        if (!(Yii::$app->authManager->checkAccess($user->id, 'permission_shop_buh'))) {
            // Если не (менеджер)
            if (!(Yii::$app->authManager->checkAccess($user->id, 'permission_shop_manager'))) {
                // Проверяю доступ
                if ($bill->user_id != Yii::$app->user->id) {
                    return $this->render('@avatar/views/site/error', ['name' => 'Ошибка', 'message' => 'Это не ваш счет']);
                }
            }
        }

        return $this->render(['bill' => $bill]);
    }

    public function actionInputRub($id)
    {
        $model = new \shop\models\validate\CabinetWalletInputRub();

        if (Yii::$app->request->isPost) {
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $s = $model->save();

                return self::jsonSuccess($s);
            } else {

                return self::jsonErrorId(102, $model->getErrors102());
            }
        }

        return $this->render([
            'model' => $model,
        ]);
    }

    public function actionInputMarketSuccess($id)
    {
        return $this->render([
        ]);
    }

    public function actionInputRubSuccess($id)
    {
        return $this->render([
        ]);
    }

    public function actionInputMarket($id)
    {
        return $this->render();
    }

    public function actionSend($id)
    {
        try {
            $bill = UserBill::findOne($id);
            if ($bill->user_id != Yii::$app->user->id) {
                return $this->render('@avatar/views/site/error', ['name' => 'Ошибка', 'message' => 'Это не ваш счет']);
            }
        } catch (\Exception $e) {
            throw new Exception('Счет не найден');
        }

        // проверка на возможность отправлять средства
        $isShowSend = true;
        if ($bill->currency == \common\models\avatar\Currency::MARKET) {
            $cInt = \common\models\piramida\Currency::findOne(['code' => 'MAR']);
            $UserBill2 = \common\models\UserBill2::findOne(['user_id' => Yii::$app->user->id, 'currency_id' => $cInt->id]);
            $w = \common\models\piramida\Wallet::findOne($UserBill2->wallet_id);
            if ((Yii::$app->user->identity->market_till < time()) || (Yii::$app->user->identity->market_till == 0) || ($w->amount == 0)) {
                $isShowSend = false;
            }
        }
        if (!$isShowSend) {
            return $this->render('@avatar/views/site/error', ['name' => 'Ошибка', 'message' => 'Переводы и зачисление средств на баланс недоступны без активации аккаунта. Активируйте его покупкой любого "Пакета возможностей" ' . \yii\helpers\Html::a('здесь', 'https://topmate.one/cabinet-market/index')]);
        }

        $model = new \avatar\models\forms\SendAtom2();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $t = $model->action();
            Yii::$app->session->setFlash('form', $t->getAddress());
        }

        return $this->render([
            'bill'   => $bill,
            'model'  => $model,
        ]);
    }

    public function actionConvert($id)
    {
        try {
            $bill = UserBill::findOne($id);
            if ($bill->user_id != Yii::$app->user->id) {
                return $this->render('@avatar/views/site/error', ['name' => 'Ошибка', 'message' => 'Это не ваш счет']);
            }
        } catch (\Exception $e) {
            throw new Exception('Счет не найден');
        }

        $model = new \avatar\models\forms\ConvertSbp();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $ret = $model->action();
            Yii::$app->session->setFlash('form', $ret);
        }

        return $this->render([
            'bill'   => $bill,
            'model'  => $model,
        ]);
    }


    public function actionDelete()
    {
        $model = new \avatar\models\validate\CabinetWalletControllerDelete();

        if (!$model->load(Yii::$app->request->post(), '')) {
            return self::jsonErrorId(400, 'Не загружены данные');
        }
        if (!$model->validate()) {
            return self::jsonErrorId(103, $model->errors);
        }
        $result = $model->action();
        if (!$result) return self::jsonErrorId(2, 'Кошелек не пустой');

        return self::jsonSuccess();
    }

    public function actionDeleteAgree()
    {
        $model = new \avatar\models\validate\CabinetWalletControllerDeleteAgree();

        if (!$model->load(Yii::$app->request->post(), '')) {
            return self::jsonErrorId(400, 'Не загружены данные');
        }
        if (!$model->validate()) {
            return self::jsonErrorId(103, $model->errors);
        }
        $model->action();

        return self::jsonSuccess();
    }
}

shop/controllers/ShopController.php
<?php

namespace shop\controllers;

use avatar\models\forms\Contact;
use avatar\services\LogReader;
use common\components\providers\ETH;
use common\components\sms\IqSms;
use common\models\avatar\Currency;
use common\models\avatar\UserBill;
use common\models\CompanyCustomizeItem;
use common\models\CurrencyIO;
use common\models\PaymentBitCoin;
use common\models\shop\Basket;
use common\models\shop\CatalogItem;
use common\models\shop\Product;
use common\models\shop\Request;
use common\models\ShopRequest;
use common\models\ShopRequestProduct;
use common\models\UserAvatar;
use common\models\UserRegistration;
use common\payment\BitCoinBlockTrailPayment;
use cs\Application;
use cs\base\BaseController;
use cs\services\Security;
use cs\services\UploadFolderDispatcher;
use cs\services\VarDumper;
use cs\web\Exception;
use iAvatar777\services\FormAjax\DefaultFormAjax;
use Yii;
use yii\base\Event;
use yii\base\UserException;
use yii\db\Connection;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\helpers\Url;
use yii\web\ForbiddenHttpException;
use yii\web\Response;

class ShopController extends \avatar\base\BaseController
{
    public function actions()
    {
        return [
            'cart-update' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\avatar\models\validate\ShopCartUpdate',
            ],
            'validate-code' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\avatar\models\forms\shop\ValidateCode',
            ],
            'cart-add' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\avatar\models\forms\shop\CartAdd',
            ],
            'cart-delete' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\avatar\models\forms\shop\CartDelete',
            ],
            'cart-delete2' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\avatar\models\forms\shop\CartDelete2',
            ],
            'first' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\avatar\models\validate\ShopFirst',
            ],
            'request-start' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\shop\models\validate\ShopRequestFirst',
            ],
            'mail' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Landing',
            ],
            'login' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Login',
            ],
            'request-add' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Request',
                'formName'    => 'Request',
            ],
            'request2-guest' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Request2',
            ],
            'request2-login' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Request2Login',
                'formName'    => 'Request2Login',
            ],
            'request3-guest' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Request3',
            ],
            'request3-login' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Request3Login',
                'formName' => 'Request3Login',
            ],
            'request4-guest' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Request4Guest',
            ],
            'request5-pay' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\shop\models\forms\Request5Pay',
            ],
            'request5-pay-rub' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\shop\models\forms\Request5PayRub',
            ],
        ];
    }

    /**
     */
    public function actionTable()
    {
        return $this->render();
    }

    /**
     */
    public function actionAdd()
    {
        return $this->render();
    }

    /**
     */
    public function actionRegion()
    {
        $model = new \shop\models\forms\ShopAdd(['type' => \common\models\ShopAll::TYPE_REGION]);

        if (Yii::$app->request->isPost) {
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $s = $model->save();

                return self::jsonSuccess($s);
            } else {
                return self::jsonErrorId(102, $model->getErrors102());
            }
        }

        return $this->render(['model' => $model]);
    }

    /**
     */
    public function actionIndex()
    {
        return $this->render();
    }

    /**
     */
    public function actionCatalog($id)
    {
        $catalog = CatalogItem::findOne($id);

        return $this->render([
            'catalog' => $catalog,
        ]);
    }


    /**
     */
    public function actionItem($id)
    {
        $Product = Product::findOne($id);
        if (is_null($Product)) {
            throw new Exception('Не найден продукт');
        }

        return $this->render([
            'item' => $Product,
        ]);
    }

    /**
     * Показыват форму авторизации/регистрации
     */
    public function actionRequest0()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['auth/login']);
        } else {
            return $this->redirect(['request1']);
        }
    }

    /**
     */
    public function actionRequest1()
    {
        return $this->render([]);
    }

    /**
     */
    public function actionRequest()
    {
        $data = Yii::$app->session->get(\shop\models\forms\Request::$keySession);
        if (!isset($data['is_guest'])) {
            if (!Yii::$app->user->isGuest) {
                $data['is_guest'] = false;
                Yii::$app->session->set(\shop\models\forms\Request::$keySession, $data);
            }
        }

        return $this->render([]);
    }

    /**
     *
     */
    public function actionRequest2()
    {
        if (!isset($data['is_guest'])) {
            if (!Yii::$app->user->isGuest) {
                $data['is_guest'] = false;
                Yii::$app->session->set(\shop\models\forms\Request::$keySession, $data);
            }
        }

        return $this->render([]);
    }

    /**
     *
     */
    public function actionRequest3()
    {
        return $this->render([]);
    }

    /**
     *
     */
    public function actionRequest4()
    {
        return $this->redirect(['request5']);
    }

    /**
     */
    public function actionRequest5()
    {
        return $this->render();
    }

    /**
     * Отправляет код
     */
    public function actionSendCode()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $code = Yii::$app->session->get('dogovor_code');
        if (is_null($code)) {
            $code = Security::generateRandomString();
            Yii::$app->session->set('dogovor_code', $code);
        }
        /** @var UserAvatar $user */
        $user = Yii::$app->user->identity;
        $walletEscrow = \Yii::$app->params['walletEscrow'];

        \common\services\Subscribe::sendArray(
            [$user->email],
            'Код для подписания договора оферты',
            'oferta',
            [
                'code' => $code,
            ]
        );

        return self::jsonSuccess();
    }


    /**
     * Показывает корзину
     */
    public function actionCart()
    {
        return $this->render();
    }

}

shop/views/cabinet-wallet/convert.php
<?php

/** @var $this \yii\web\View */
/** @var $bill \common\models\avatar\UserBill */
/** @var $model \avatar\models\forms\ConvertSbp */

use common\models\avatar\UserBill;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

$this->title = 'Конвертация';

\avatar\assets\Notify::register($this);
\avatar\assets\Clipboard::register($this);

?>
<?php
$this->registerJs(<<<JS

var clipboard = new Clipboard('.buttonCopy');
clipboard.on('success', function(e) {

    new Noty({
        timeout: 1000,
        theme: 'sunset',
        type: 'success',
        layout: 'bottomLeft',
        text: 'Скопировано'
    }).show();

});

JS
);
?>

<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header text-center"><?= Html::encode($this->title) ?></h1>
    </div>

    <div class="col-lg-12">

        <?php
        /** @var  $currencyELXT \common\models\avatar\Currency */
        $currencyELXT = $bill->getCurrencyObject();

        $userWallet = $bill;
        $wallet = \common\models\piramida\Wallet::findOne($userWallet->address);
        $currency = $wallet->getCurrency();
        Yii::$app->session->set('currency.decimals', $currency->decimals);
        ?>

        <p class="text-center">
            <img src="<?= $currencyELXT->image ?>" width="300" style="margin-top: 30px;" class="img-circle">
        </p>
        <?php
        $address = $wallet->getAddress();
        $options = [
            'data'  => [
                'toggle'         => 'tooltip',
                'clipboard-text' => $address,
            ],
            'class' => 'buttonCopy',
            'title' => 'Адрес кошелька. Нажми чтобы скопировать',
        ];
        ?>
        <p class="text-center"><code <?= Html::renderTagAttributes($options) ?>><?= $address ?></code></p>
        <p class="text-center"><?= $currencyELXT->title ?></p>
        <h3 class="page-header text-center"><?= Yii::$app->formatter->asDecimal($wallet->getAmountWithDecimals(), $currency->decimals) ?></h3>
        <p class="text-center"><span class="label label-info"><?= $currencyELXT->code ?></span></p>

        <?php if (Yii::$app->session->hasFlash('form')) { ?>

            <?php $ret = Yii::$app->session->getFlash('form'); ?>
            <div class="alert alert-success">
                Успешно сконверитровано.
            </div>

            <p>
                <a href="<?= \yii\helpers\Url::to(['cabinet-wallet/item', 'id' => $bill->id]) ?>" class="btn btn-success">Этот кошелек</a>
                <a href="<?= \yii\helpers\Url::to(['cabinet-bills/index']) ?>" class="btn btn-success">Все кошельки</a>
            </p>

        <?php  } else { ?>


            <div class="row">
                <div class="col-lg-5">

                    <?php $form = \yii\bootstrap\ActiveForm::begin([
                        'options' => ['enctype' => 'multipart/form-data']
                    ]); ?>
                    <?= Html::hiddenInput(Html::getInputName($model, 'id'), $bill->id) ?>
                    <?= $form->field($model, 'amount')->label('Монет для пересылки') ?>

                    <hr>
                    <div class="form-group">
                        <?= Html::submitButton('Обменять', [
                            'class' => 'btn btn-default',
                            'name'  => 'contact-button',
                            'style' => 'width:100%',
                        ]) ?>
                    </div>
                    <?php \yii\bootstrap\ActiveForm::end(); ?>
                </div>
            </div>

        <?php } ?>
    </div>
</div>

shop/views/cabinet-wallet/index.php
<?php

/** $this \yii\web\View  */

use common\models\avatar\UserBill;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

$this->title = 'Кошелек';


?>

<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
    </div>

    <div class="col-lg-12">

        <?php
        $this->registerJS(<<<JS
$('.buttonAdd').click(function() {
    $('#modalAdd').modal();
});
JS
        );
        ?>



        <?php \yii\widgets\Pjax::begin(); ?>
        <?php
        $this->registerJS(<<<JS
$('[data-toggle="tooltip"]').tooltip();

$('.rowTable').click(function(e) {
    window.location = '/cabinet-wallet/item' + '?' + 'id' + '=' + $(this).data('id');
});
$('.buttonCard').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-cards/card' + '?' + 'id' + '=' + $(this).data('id');
});

$('.buttonDelete').click(function (e) {
    e.preventDefault();
    e.stopPropagation();
    if (confirm('Подтвердите удаление')) {
        var button = $(this);
        var id = $(this).data('id');
        ajaxJson({
            url: '/cabinet-wallet/delete',
            data: {id: id},
            success: function (ret) {
                $('#modalInfo').on('hidden.bs.modal', function() {
                    button.parent().parent().remove();
                }).modal();
            },
            errorScript: function(ret) {
                if (ret.id == 2) {
                    $('.buttonDeleteAgree').attr('data-id', id);
                    
                    // Кошелек не пустой
                    $('#modalQuestion').modal();
                }
            }
        });
    }
});
JS
        );
        ?>
        <?= \yii\grid\GridView::widget([
            'dataProvider' => new \yii\data\ActiveDataProvider([
                'query'      => UserBill::find()
                    ->where(['user_id' => Yii::$app->user->id])
                    ->andWhere(['mark_deleted' => 0])
                ,
                'pagination' => [
                    'pageSize' => 20,
                ],
            ]),
            'summary' => '',
            'tableOptions' => [
                'class' => 'table table-striped table-hover',
            ],
            'rowOptions'   => function ($item) {
                $data = [
                    'data'  => ['id' => $item['id']],
                    'role'  => 'button',
                    'class' => 'rowTable',
                ];
                return $data;
            },
            'columns'      => [
                [
                    'header'    => 'WID',
                    'content'   => function (\common\models\avatar\UserBill $item) {
                        $currency = $item->currency;
                        if (!\common\models\avatar\CurrencyLink::find()->where(['currency_ext_id' => $currency])->exists()) {
                            return '';
                        }
                        $v = \yii\helpers\ArrayHelper::getValue($item, 'address');
                        if (is_null($v)) return '';
                        $w = new \common\models\piramida\Wallet(['id' => $v]);
                        $addressShort = $w->getAddressShort();

                        return Html::tag('code', $addressShort);
                    },
                ],
                [
                    'header'  => 'Картинка',
                    'content' => function ($item) {
                        $i = ArrayHelper::getValue($item, 'currency', '');
                        if ($i == '') return '';
                        $currency = \common\models\avatar\Currency::findOne($i);
                        if (is_null($currency)) return '';

                        return Html::img($currency->image, [
                            'class'  => "img-circle",
                            'width'  => 60,
                            'height' => 60,
                            'style'  => 'margin-bottom: 0px;',
                        ]);
                    },
                ],
                [
                    'header'  => 'Название',
                    'content' => function ($item) {
                        return $item['name'];
                    },
                ],

                [
                    'header'         => 'Монет',
                    'headerOptions'  => ['class' => 'text-right'],
                    'contentOptions' => ['class' => 'text-right'],
                    'content'        => function ($item) {
                        $i = ArrayHelper::getValue($item, 'currency', '');
                        if ($i == '') return '';
                        $currency = \common\models\avatar\Currency::findOne($i);
                        if (is_null($currency)) return '';

                        if (in_array($currency->id, \common\models\avatar\CurrencyLink::find()->select(['currency_ext_id'])->column())) {
                            $wallet = \common\models\piramida\Wallet::findOne($item['address']);
                            if (is_null($wallet)) return '';

                            return Yii::$app->formatter->asDecimal($wallet->getAmountWithDecimals(), 2);
                        }

                        return '';
                    },
                ],
                [
                    'header'  => 'Валюта',
                    'content' => function ($item) {
                        $i = ArrayHelper::getValue($item, 'currency', '');
                        if ($i == '') return '';
                        $currency = \common\models\avatar\Currency::findOne($i);
                        if (is_null($currency)) return '';

                        return Html::tag('span', $currency->code, ['class' => 'label label-info']);
                    },
                ],
                [
                    'header'  => 'Карта',
                    'content' => function ($item) {
                        $i = ArrayHelper::getValue($item, 'card_id', '');
                        if ($i == '') return '';
                        return Html::button('Карта', [
                            'class' => 'btn btn-primary buttonCard',
                            'data' => [
                                'id' => $item['card_id'],
                            ],
                        ]);
                    },
                ],
                [
                    'header'  => 'Удалить',
                    'content' => function ($item) {
                        return Html::button('Удалить', [
                            'class' => 'btn btn-danger btn-xs buttonDelete',
                            'data'  => [
                                'id' => $item['id'],
                            ],
                        ]);
                    },
                ], ],
        ]) ?>
        <?php \yii\widgets\Pjax::end(); ?>
    </div>
</div>

<div class="modal fade" id="modalAdd" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Информация</h4>
            </div>
            <div class="modal-body">
                <form id="form_1">
                    <div class="form-group field-name">
                        <label class="control-label">Наименование</label>
                        <input type="text" class="form-control text-input" name="name" aria-required="true" aria-invalid="true">
                        <p class="help-block help-block-error" style="display: none;"></p>
                    </div>
                    <div class="form-group field-currency_id">
                        <label class="control-label">Валюта</label>
                        <select class="form-control" name="currency_id">
                            <option value="">- Ничего не выбрано -</option>
                            <?php $items = \common\models\avatar\Currency::find()
                                ->where(['id' => [9, 10]])
                                ->all() ?>
                            <?php foreach ($items as $c) { ?>
                                <option value="<?= $c->id ?>"><?= $c->title ?> (<?= $c->code ?>)</option>
                            <?php } ?>
                        </select>
                        <p class="help-block help-block-error" style="display: none;"></p>
                    </div>

                </form>
            </div>
            <div class="modal-footer">

                <?php
                $this->registerJS(<<<JS

var buttonAddExecute = function(e) {
    e.preventDefault();
    e.stopPropagation();
    var b = $(this);
    var bText = b.html();
    b.off('click');
    b.html($('<i>', {class: 'fa fa-spinner fa-spin fa-fw'}));
    b.attr('disabled', 'disabled');
    
    ajaxJson({
        url: '/cabinet-wallet/add',
        data: $('#form_1').serializeArray(),
        success: function (ret) {
            b.on('click', buttonAddExecute);
            b.html(bText);
            b.removeAttr('disabled');
            
            window.location.reload();
        },
        errorScript: function(ret) {
            switch (ret.id) {
                case 102:
                    var f = $('#form_1');
                    $.each(ret.data,function(i,v) {
                        var name = v.name;
                        var value = v.value;
                        var t = f.find('.field-' + name);
                        t.addClass('has-error');
                        t.find('p.help-block-error').html(value.join('<br>')).show();
                    });
                    
                    break;
            }
            
            b.on('click', buttonAddExecute);
            b.html(bText);
            b.removeAttr('disabled');
        }
    });
};

$('.buttonAddExecute').click(buttonAddExecute);
$('#form_1 .form-control').on('focus', function() {
    var o = $(this);
    var p = o.parent();
    if (p.hasClass('input-group')) {
        p = p.parent();
    }
    p.removeClass('has-error');
    p.find('p.help-block-error').hide();
});
JS
                );
                ?>
                <button type="button" class="btn btn-primary buttonAddExecute" >Добавить</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalQuestion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Информация</h4>
            </div>
            <div class="modal-body">
                Кошелек не пустой, подтвердите удаление
            </div>
            <div class="modal-footer">
                <?php
                $this->registerJS(<<<JS
$('.buttonDeleteAgree').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    ajaxJson({
        url: '/cabinet-wallet/delete-agree',
        data: {id: $(this).data('id')},
        success: function (ret) {
            window.location.reload();
        }
    });
});
JS
                );
                ?>
                <button type="button" class="btn btn-danger buttonDeleteAgree">Удалить</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Информация</h4>
            </div>
            <div class="modal-body">
                Успешно!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

shop/views/cabinet-wallet/input-market-success.php
<?php

/** @var $this \yii\web\View */
/** @var $model \shop\models\validate\CabinetWalletInputRub */

use common\models\avatar\UserBill;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

$this->title = 'Успешно';


?>


<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header text-center"><?= Html::encode($this->title) ?></h1>
    </div>

    <div class="col-lg-12">
        <p>Успешно</p>

    </div>
</div>