shop/controllers/ShopController.php
<?php

namespace shop\controllers;

use avatar\models\forms\Contact;
use avatar\services\LogReader;
use common\components\providers\ETH;
use common\components\sms\IqSms;
use common\models\avatar\Currency;
use common\models\avatar\UserBill;
use common\models\CompanyCustomizeItem;
use common\models\CurrencyIO;
use common\models\PaymentBitCoin;
use common\models\shop\Basket;
use common\models\shop\CatalogItem;
use common\models\shop\Product;
use common\models\shop\Request;
use common\models\ShopRequest;
use common\models\ShopRequestProduct;
use common\models\UserAvatar;
use common\models\UserRegistration;
use common\payment\BitCoinBlockTrailPayment;
use cs\Application;
use cs\base\BaseController;
use cs\services\Security;
use cs\services\UploadFolderDispatcher;
use cs\services\VarDumper;
use cs\web\Exception;
use iAvatar777\services\FormAjax\DefaultFormAjax;
use Yii;
use yii\base\Event;
use yii\base\UserException;
use yii\db\Connection;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\helpers\Url;
use yii\web\ForbiddenHttpException;
use yii\web\Response;

class ShopController extends \avatar\base\BaseController
{
    public function actions()
    {
        return [
            'cart-update' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\avatar\models\validate\ShopCartUpdate',
            ],
            'validate-code' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\avatar\models\forms\shop\ValidateCode',
            ],
            'cart-add' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\avatar\models\forms\shop\CartAdd',
            ],
            'cart-delete' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\avatar\models\forms\shop\CartDelete',
            ],
            'cart-delete2' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\avatar\models\forms\shop\CartDelete2',
            ],
            'first' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\avatar\models\validate\ShopFirst',
            ],
            'request-start' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\shop\models\validate\ShopRequestFirst',
            ],
            'mail' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Landing',
            ],
            'login' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Login',
            ],
            'request-add' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Request',
                'formName'    => 'Request',
            ],
            'request2-guest' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Request2',
            ],
            'request2-login' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Request2Login',
                'formName'    => 'Request2Login',
            ],
            'request3-guest' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Request3',
            ],
            'request3-login' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Request3Login',
                'formName' => 'Request3Login',
            ],
            'request4-guest' => [
                'class'    => '\iAvatar777\services\FormAjax\DefaultFormAjax',
                'model'    => '\shop\models\forms\Request4Guest',
            ],
            'request5-pay' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\shop\models\forms\Request5Pay',
            ],
            'request5-pay-rub' => [
                'class'    => '\avatar\controllers\actions\DefaultAjax',
                'model'    => '\shop\models\forms\Request5PayRub',
            ],
        ];
    }

    /**
     */
    public function actionTable()
    {
        return $this->render();
    }

    /**
     */
    public function actionAdd()
    {
        return $this->render();
    }

    /**
     */
    public function actionRegion()
    {
        $model = new \shop\models\forms\ShopAdd(['type' => \common\models\ShopAll::TYPE_REGION]);

        if (Yii::$app->request->isPost) {
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $s = $model->save();

                return self::jsonSuccess($s);
            } else {
                return self::jsonErrorId(102, $model->getErrors102());
            }
        }

        return $this->render(['model' => $model]);
    }

    /**
     */
    public function actionIndex()
    {
        return $this->render();
    }

    /**
     */
    public function actionCatalog($id)
    {
        $catalog = CatalogItem::findOne($id);

        return $this->render([
            'catalog' => $catalog,
        ]);
    }


    /**
     */
    public function actionItem($id)
    {
        $Product = Product::findOne($id);
        if (is_null($Product)) {
            throw new Exception('Не найден продукт');
        }

        return $this->render([
            'item' => $Product,
        ]);
    }

    /**
     * Показыват форму авторизации/регистрации
     */
    public function actionRequest0()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['auth/login']);
        } else {
            return $this->redirect(['request1']);
        }
    }

    /**
     */
    public function actionRequest1()
    {
        return $this->render([]);
    }

    /**
     */
    public function actionRequest()
    {
        $data = Yii::$app->session->get(\shop\models\forms\Request::$keySession);
        if (!isset($data['is_guest'])) {
            if (!Yii::$app->user->isGuest) {
                $data['is_guest'] = false;
                Yii::$app->session->set(\shop\models\forms\Request::$keySession, $data);
            }
        }

        return $this->render([]);
    }

    /**
     *
     */
    public function actionRequest2()
    {
        if (!isset($data['is_guest'])) {
            if (!Yii::$app->user->isGuest) {
                $data['is_guest'] = false;
                Yii::$app->session->set(\shop\models\forms\Request::$keySession, $data);
            }
        }

        return $this->render([]);
    }

    /**
     *
     */
    public function actionRequest3()
    {
        return $this->render([]);
    }

    /**
     *
     */
    public function actionRequest4()
    {
        return $this->redirect(['request5']);
    }

    /**
     */
    public function actionRequest5()
    {
        return $this->render();
    }

    /**
     * Отправляет код
     */
    public function actionSendCode()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $code = Yii::$app->session->get('dogovor_code');
        if (is_null($code)) {
            $code = Security::generateRandomString();
            Yii::$app->session->set('dogovor_code', $code);
        }
        /** @var UserAvatar $user */
        $user = Yii::$app->user->identity;
        $walletEscrow = \Yii::$app->params['walletEscrow'];

        \common\services\Subscribe::sendArray(
            [$user->email],
            'Код для подписания договора оферты',
            'oferta',
            [
                'code' => $code,
            ]
        );

        return self::jsonSuccess();
    }


    /**
     * Показывает корзину
     */
    public function actionCart()
    {
        return $this->render();
    }

}

shop/views/shop/_menu3.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\db\Query;
use yii\helpers\Url;

/* меню в кабинете, табуляция, недоделана */



/* @var $this yii\web\View */
$requestedRoute = Yii::$app->requestedRoute;


$menu = [
    [
        'url'     => '/page/item?id=54',
        'label'   => 'Как все работает',
        'urlList' => [
            ['startsWith', '/page/item?id=54'],
        ],
    ],
    [
        'url'     => ['shop/index'],
        'label'   => 'Федеральные и сетевые',
        'urlList' => [
            ['route', 'shop/index'],
        ],
    ],
    [
        'url'     => ['shop/region'],
        'label'   => 'Региональные и местные',
        'urlList' => [
            ['route', 'shop/region'],
        ],
    ],
    [
        'url'     => ['shop/add'],
        'label'   => 'Добавьте магазин',
        'urlList' => [
            ['route', 'shop/add'],
        ],
    ],
    [
        'url'     => '/page/item?id=41',
        'label'   => 'Оплата баллами',
        'urlList' => [
            ['startsWith', '/page/item?id=41'],
        ],
    ],
    [
        'url'     => '/page/item?id=92',
        'label'   => 'Дисклеймер',
        'urlList' => [
            ['startsWith', '/page/item?id=92'],
        ],
    ],
];

function hasRoute12($item, $route)
{
    if (isset($item['items'])) {
        foreach ($item['items'] as $i) {
            if (isset($i['route'])) {
                if ($i['route'] == $route) {
                    return true;
                }
            }
        }
    }
    if (isset($item['route'])) {
        if ($item['route'] == $route) return true;
    }
    if (\yii\helpers\ArrayHelper::keyExists('urlList', $item)) {
        foreach ($item['urlList'] as $i) {
            switch ($i[0]) {
                case 'route':
                    if ($route == $i[1]) return true;
                    break;
                case 'startsWith':
                    if (\yii\helpers\StringHelper::startsWith($route, $i[1])) return true;
                    break;
                case 'controller':
                    $arr = explode('/', $route);
                    if ($arr[0] == $i[1]) return true;
                    break;
            }
        }
    }

    return false;
}

?>

<ul class="nav nav-tabs">
    <?php
    foreach ($menu as $item) {
        $optionsLI = [];
        $options = ['class' => []];
        if (hasRoute12($item, Yii::$app->requestedRoute)) {
            $optionsLI['class'][] = 'active';
        }

        $optionsClass = (isset($optionsLI['class']))? join(' ', $options['class']) : '';
        if ($optionsClass != '') $options['class'] = $optionsClass;
        $optionsLiClass = (isset($optionsLI['class']))? join(' ', $optionsLI['class']) : '';
        if ($optionsLiClass != '') $optionsLI['class'] = $optionsLiClass;

        echo Html::tag(
            'li',
            Html::a($item['label'], $item['url'], $options),
            $optionsLI
        );
    }
    ?>
</ul>

shop/views/shop/add.php
<?php

use common\models\avatar\Currency;
use common\models\avatar\UserBill;
use yii\helpers\Html;
use yii\helpers\Url;

/** @var $this yii\web\View */


$this->title = 'Добавьте ваш магазин';



?>
<?php
$this->registerJs(<<<JS

//при нажатию на любую кнопку, имеющую класс .btn
$("#modalHelp").click(function() {
    //открыть модальное окно с id="myModal"
    $("#myModal").modal('show');
});

JS
);
?>
<div class="container" style="padding-bottom: 70px;">
    <div class="col-lg-12" style="margin-bottom: 30px;">
        <h1 class="page-header text-center">
            <?= $this->title ?>
            <a href="#" id="modalHelp"><i title="Помощь" class="fas fa-question-circle c-link" style="font-size: 30px;float: right;padding-top: 5px;"></i></a>
        </h1>

        <div id="myModal" class="modal fade" tabindex="-1" role="document" aria-labelledby="myLargeModalLabel">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <?php
                        $id = 67;
                        $page = \common\models\exchange\Page::findOne($id);

                        $pageLang = \common\models\PageLang::findOne(['parent_id' => $id, 'language' => Yii::$app->language]);
                        if (is_null($pageLang)) {
                            $name = $page->name;
                            $content = $page->content;
                        } else {
                            $name = $pageLang->name;
                            $content = $pageLang->content;
                        }
                        ?>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"><?= $name ?></h4>
                    </div>
                    <div class="modal-body">
                        <?= $content ?>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?= \Yii::t('c.XwLuZKjn6M', 'Закрыть') ?></button>
                    </div>
                </div>
            </div>
        </div>
        <?= $this->render('_menu3') ?>

    </div>
    <div class="col-lg-1">

    </div>
    <div class="col-sm-10">

        <?= $content ?>

    </div>



</div>

shop/views/shop/cart.php
<?php

use common\models\avatar\Currency;
use common\models\avatar\UserBill;
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\touchspin\TouchSpin;

/** @var $this yii\web\View */
/** @var $school \common\models\school\School */


$this->title = 'Корзина';


?>

<div class="container" style="padding-bottom: 70px;">
    <div class="col-lg-12">
        <h1 class="page-header text-center">
            <?= $this->title ?>
        </h1>
    </div>

    <div class="col-lg-8 col-lg-offset-2">

        <div class="row">
            <?php
            $items = \common\models\shop\Basket::get();
            $rows = [];
            foreach ($items as $i) {
                $rows[] = [
                    'id'          => $i['id'],
                    'count'       => $i['count'],
                    'name'        => $i['product']['name'],
                    'image'       => $i['product']['image'],
                    'price'       => $i['product']['price'],
                    'currency_id' => $i['product']['currency_id'],
                ];
            }
            ?>
            <?php
            $this->registerJS(<<<JS
$('.buttonDelete').click(function (e) {
    e.preventDefault();
    e.stopPropagation();
    if (confirm('Подтвердите удаление')) {
        var button = $(this);
        var id = $(this).data('id');
        ajaxJson({
            url: '/shop/cart-delete',
            data: {id: id},
            success: function (ret) {
                $('#modalInfo').on('hidden.bs.modal', function() {
                    button.parent().parent().remove();
                }).modal();
            }
        });
    }
});
$('.inputI').on('change', function (e) {
    e.preventDefault();
    e.stopPropagation();
    var t = $(this);
    var id = t.data('id');
    
    ajaxJson({
        url: '/shop/cart-update',
        data: {
            id: id,
            count: t.val()
        },
        success: function (ret) {
            $('.sumAll').html(ret.allSumFormatted);
        }
    });
});
$('.inputI').on('input', function (e) {
    e.preventDefault();
    e.stopPropagation();
    var t = $(this);
    var id = t.data('id');
    
    ajaxJson({
        url: '/shop/cart-update',
        data: {
            id: id,
            count: t.val()
        },
        success: function (ret) {
            $('.sumAll').html(ret.allSumFormatted);
        }
    });
});


JS
            );
            ?>
            <?= \yii\grid\GridView::widget([
                'dataProvider' => new \yii\data\ArrayDataProvider([
                    'allModels' => $rows,
                ]),
                'tableOptions' => [
                    'class' => 'table table-striped table-hover table_exchange',
                ],
                'rowOptions'   => function ($item) {
                    $data = [
                        'data'  => ['id' => $item['id']],
                        'role'  => 'button',
                        'class' => 'rowTable',
                    ];
                    return $data;
                },
                'columns' => [
                    [
                        'attribute' => 'id',
                        'contentOptions' => ['aria-label' => 'ID'],
                    ],
                    [
                        'header'  => 'Картинка',
                        'contentOptions' => ['class' => 'text-right','aria-label' => 'Картинка'],
                        'content' => function ($item) {
                            $i = \yii\helpers\ArrayHelper::getValue($item, 'image', '');
                            if ($i == '') return '';

                            return Html::img(\common\widgets\FileUpload7\FileUpload::getFile($i, 'crop'), [
                                'class'  => "thumbnail",
                                'width'  => 80,
                                'height' => 80,
                                'style'  => 'margin-bottom: 0px;',
                            ]);
                        },
                    ],
                    [
                        'header'         => 'Наименование',
                        'attribute' => 'name',
                        'contentOptions' => ['aria-label' => 'Наименование'],
                    ],
                    [
                        'header'         => 'Цена',
                        'headerOptions'  => ['class' => 'text-right'],
                        'contentOptions' => ['class' => 'text-right','aria-label' => 'Цена'],
                        'content'        => function ($item) {
                            $cid = \yii\helpers\ArrayHelper::getValue($item, 'currency_id');
                            if (is_null($cid)) return '';
                            $c = Currency::findOne($cid);
                            $v = \yii\helpers\ArrayHelper::getValue($item, 'price', 0);
                            if ($v == 0) return '';
                            $cHtml = Html::tag('span', $c->code, ['class' => 'label label-info', 'style' => 'margin-left:5px;']);

                            return Yii::$app->formatter->asDecimal($v / pow(10, $c->decimals), $c->decimals) . $cHtml;
                        },
                    ],
                    [
                        'header'         => 'Стоимость',
                        'attribute'      => 'count',
                        'contentOptions' => ['class' => 'text-right', 'style' => 'width: 150px;','aria-label' => 'Кол-во'],
                        'content'        => function ($item) {
                            return TouchSpin::widget([
                                'name'          => 'volume',
                                'options'       => ['placeholder' => 'Adjust...', 'class' => 'form-control inputI', 'data-id' => $item['id']],
                                'pluginOptions' => [
                                    'initval' => $item['count'],
                                    'step'    => 1,
                                    'max'     => 1000000000,
                                ],
                            ]);
                        },
                    ],
                    [
                        'header'  => 'Удалить',
                        'content' => function ($item) {
                            return Html::button('Удалить', [
                                'class' => 'btn btn-danger btn-xs buttonDelete',
                                'data'  => [
                                    'id' => $item['id'],
                                ]
                            ]);
                        }
                    ],
                ]
            ]) ?>


            <p>Комментарий:</p>
            <textarea id="comment" class="form-control" style="margin-bottom: 50px;" rows="5"></textarea>

            <?php
            $p = \common\models\shop\Basket::getPrice();
            $c = Currency::findOne(6);
            $cHtml = Html::tag('span', $c->code, ['class' => 'label label-info', 'style' => 'margin-left:5px;']);

            $this->registerJs(<<<JS
$('.buttonFirst').click(function(e) {
    ajaxJson({
        url: '/shop/first',
        data: {comment: $('#comment').val()},
        success: function(ret) {
            window.location = '/shop/order';
        }
    });
});
JS
            );
            ?>
            <p>Итого: <span class="sumAll"><?= Yii::$app->formatter->asDecimal($p / pow(10, $c->decimals), $c->decimals) . $cHtml ?></span></p>

            <p><button class="btn c-order buttonFirst">Оформить</button></p>
        </div>

    </div>
</div>


<div class="modal fade" id="modalInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Информация</h4>
            </div>
            <div class="modal-body">
                Успешно!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

shop/views/shop/item.php
<?php

use common\models\avatar\Currency;
use common\models\avatar\UserBill;
use yii\helpers\Html;
use yii\helpers\Url;

/** @var $this yii\web\View */
/** @var $school \common\models\school\School */
/** @var $item \common\models\shop\Product */


$this->title = 'Товар #'.$item->id;


?>

<div class="container" style="padding-bottom: 70px;">
    <div class="col-lg-12">
        <h1 class="page-header">
            <?= $item->name ?>
        </h1>
    </div>

    <div class="col-lg-4">
        <p><img src="<?= $item->image ?>" width="100%"></p>
    </div>
    <div class="col-lg-8">
        <?php
        $currency = Currency::findOne($item->currency_id);
        $price = $item->price / pow(10, $currency->decimals);
        ?>

        <p>
            Стоимость: <?= Yii::$app->formatter->asDecimal($price, $currency->decimals) ?> <span class="label label-info"><?= $currency->code ?></span>
        </p>
        <p>
            <?= nl2br($item->content) ?>
        </p>
        <?php

        $this->registerJs(<<<JS
$('.buttonAddToCart').click(function(e) {
    ajaxJson({
        url: '/shop/cart-add',
        data: {id: $(this).data('id')},
        success: function(ret) {
            // document.getElementsByClassName("basketCounter")[0].innerHTML = ret.counter;
            // document.getElementsByClassName("basketCounter")[1].innerHTML = ret.counter;
           $('.basketCounter').html(ret.counter);
            new Noty({
                timeout: 3000,
                theme: 'relax',
                type: 'success',
                layout: 'bottomLeft',
                text: 'Товар успешно добавлен в корзину.'
            }).show();
        }
    })
});
JS
);
        ?>
        <p><button class="btn btn-success buttonAddToCart" style="width: 100%" data-id="<?= $item->id ?>">В корзину</button></p>
    </div>
</div>

shop/views/shop/pay.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/** @var $this yii\web\View */
/** @var $request \common\models\shop\Request */

$this->title = 'Оплата заявки #' . $request->id;

$billing = \common\models\BillingMain::findOne($request->billing_id);

/** @var \common\models\PaySystemConfig $config */
$config = \common\models\PaySystemConfig::findOne($billing->config_id);

$class = $config->getClass();
$ps = $config->getPaySystem();
$price = $request->sum;

// Получаю идентификато класса
$classObject = \common\models\BillingMainClass::findOne(['name' => '\\' . $request::className()]);
if (is_null($classObject)) {
    throw new Exception('Нет \common\models\BillingMainClass');
}




?>
    <div class="container">
        <div class="col-lg-12">
            <h1 class="page-header"><?= Html::encode($this->title) ?></h1>

            <?= $class->getForm(
                $billing,
                'Оплата заявки #' . $request->id,
                'Получатель: ' . 'VVFund',
                [
                    'action'     => 'shopRequest.' . $request->id,
                    'successURL' => \yii\helpers\Url::to('/cabinet-shop-requests/view?id=' . $request->id, true),
                ]
            ); ?>
        </div>
    </div>

<?php

// подтверждение платежа

$successObject = \common\models\PaySystemSuccess::findOne(['paysystem_id' => $ps->id]);

$view = '';
if (!is_null($successObject)) {
    $view = $successObject->view;

    $this->registerJs(<<<JS
$('#buttonSuccess').click(function(e) {
    $('#modalInfo').modal();
});
$('#modalInfo .buttonConfirm').click(function(e) {
    ajaxJson({
        url: '/cabinet-billing/success?id=' + {$billing->id},
        data: $('#formSuccess').serializeArray(),
        success: function(ret) {
            window.location = '/cabinet-shop-requests/view?id=' + {$request->id};
        }
    })
});

JS
    );
} else {
    $this->registerJs(<<<JS
$('#buttonSuccess').click(function(e) {
    ajaxJson({
        url: '/cabinet-billing/success?id=' + {$billing->id},
        success: function(ret) {
            window.location = '/cabinet-shop-requests/view?id=' + {$request->id};
        }
    })
});
JS
    );

}
?>

<?php if (!is_null($successObject)) { ?>
    <div class="modal fade" id="modalInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Информация</h4>
                </div>
                <div class="modal-body">
                    <?php $form = ActiveForm::begin([
                        'id'        => 'formSuccess',
                        'options'   => ['enctype' => 'multipart/form-data']
                    ]);
                    $model = $successObject->model;
                    $modelObject = new $model(['billing' => $billing]);
                    ?>

                    <?= $this->render($view, [
                        'form'  => $form,
                        'model' => $modelObject,
                    ]); ?>

                    <?php ActiveForm::end(); ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success buttonConfirm">Отправить</button>
                    <button type="button" class="btn btn-default " data-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

shop/views/shop/request-login.php
<?php
/**
 * Created by PhpStorm.
 * User: ramha
 * Date: 17.11.2020
 * Time: 8:44
 */

?>
<p>Если вы имеете аккаунт вы можете авторизоваться</p>
<p><button class="btn btn-default buttonLogin1">Войти</button></p>
<?php
$this->registerJs(<<<JS
$('.buttonLogin1').click(function(e) {
    $('.js-login').collapse('toggle');
});
JS
)
?>
<div class="collapse js-login">
    <?php $model2 = new \shop\models\forms\Login() ?>
    <?php $form = \iAvatar777\services\FormAjax\ActiveForm::begin([
        'model'                 => $model2,
        'formUrl' => '/shop/login',
        'success' => <<<JS
function (ret) {
    $('#modalInfo').on('hidden.bs.modal', function() {
        window.location.reload();
    }).modal();
}
JS
        ,
    ]); ?>

    <?= $form->field($model2, 'username') ?>
    <?= $form->field($model2, 'password')->passwordInput() ?>

    <hr>

    <?php \iAvatar777\services\FormAjax\ActiveForm::end(['label' => 'Войти']); ?>
</div>

<hr>

shop/views/shop/request1.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $model \shop\models\forms\Request2 */

$this->title = 'ВЫБЕРИТЕ ВАРИАНТЫ ЗАКАЗА';


?>

<div class="container" style="padding-bottom: 70px;">
    <div class="col-lg-12">
        <h1 class="page-header text-center">
            <?= $this->title ?>
        </h1>
    </div>

    <div class="col-lg-6 col-lg-offset-3">

        <p><a href="/phone/step1">Пополнить баланс номера телефона</a></p>
        <p><a href="/shop/request">Создать заказ на товары или услуги</a></p>

    </div>
</div>


<div class="modal fade" id="modalInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Информация</h4>
            </div>
            <div class="modal-body">
                Успешно!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>